CREATE TABLE users (
    username VARCHAR(15) UNIQUE NOT NULL PRIMARY KEY,
    passwd VARBINARY(97) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL CHECK (email LIKE '%@%'),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    post_id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(15) NOT NULL,
    title VARCHAR(40) UNIQUE NOT NULL,
    link VARCHAR(500) UNIQUE NOT NULL CHECK (link LIKE 'google.com/maps/place/%'),
    bio TEXT NOT NULL,
    rating TINYINT CHECK (rating BETWEEN 1 AND 5) NOT NULL,
    votes INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE comments (
    comment_id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(15) NOT NULL,
    post_id INT NOT NULL,
    content TEXT NOT NULL,
    votes INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES posts(post_id) ON UPDATE CASCADE ON DELETE CASCADE
);
